### ISSUE TITLE
Stateful property not syned between javascript and python in the demo

### ISSUE THREAD

**Issue by johnowhitaker** [manzt/anywidget#550] opened 2024-04-26 19:45 UTC
![Screenshot 2024-04-26 123549](https://github.com/manzt/anywidget/assets/6575163/9b889164-6d6e-4c6e-9878-d41ceaca5263)
The counter example doesn't work as expected for me - the count increments when being clicked but accessing and setting counter.count shows an unrelated value and doesn't change the displayed count in the button. 

This is in VSCode on windows. Trying in jupyter notebook v6 gives "Failed to load model class 'AnyModel' from module 'anywidget'" error.

**Comment by johnowhitaker** [comment] 2024-04-26 19:45
(In case it isn't clear in the screenshot, I clicked the button 3 times)

**Comment by manzt** [comment] 2024-04-26 20:16
Hi there, I'm not able to reproduce this in VS Code. If you can provide a minimal reproducible example (how you created the Python environment and exactly what you ran, that would  be very helpful).

> Trying in jupyter notebook v6 gives "Failed to load model class 'AnyModel' from module 'anywidget'" error.

This was a bug and I just now pushed a fix in #553. Please `pip install anywidget==0.9.10`.

**Comment by manzt** [comment] 2024-04-26 20:19
Correction: There is a bug in your code snippet. 

The traitlet is named `value` not `count`. You need to update the example...

```py
import anywidget
import traitlets

class CounterWidget(anywidget.AnyWidget):
    _esm = """
    function render({ model, el }) {
      let button = document.createElement("button");
      button.innerHTML = `count is ${model.get("value")}`;
      button.addEventListener("click", () => {
        model.set("value", model.get("value") + 1);
        model.save_changes();
      });
      model.on("change:value", () => {
        button.innerHTML = `count is ${model.get("value")}`;
      });
      el.appendChild(button);
    }
    export default { render };
    """
    value = traitlets.Int(0).tag(sync=True)
```

```diff
counter = CounterWidget()
-- counter.count = 42
++ counter.value = 42
counter
```

```diff
-- counter.count
++ counter.value
```

**Closed by manzt** 2024-04-26 20:19 UTC

**Comment by johnowhitaker** [comment] 2024-04-26 20:49
Gah sorry about that, figured it out and came to see you'd already beat me to it.
